# typed: false
# frozen_string_literal: true

# Auto-generated by CI. Do not edit manually.
# Source: https://github.com/Penterep/penterep-cli

class Penterep < Formula
  desc "AI-powered penetration testing CLI assistant"
  homepage "https://github.com/Penterep/penterep-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Penterep/penterep-cli/releases/download/v#{version}/penterep-darwin-arm64"
      sha256 "0c69af4d748a9ceddf5f3355c1eac579eb720939fd3a8ec6077097f82b207308"
    else
      url "https://github.com/Penterep/penterep-cli/releases/download/v#{version}/penterep-darwin-x64"
      sha256 "3a4d202052166de7d5c3ae0a83a0c89c1d98d5a892fa13e6efccbe243d15906e"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Penterep/penterep-cli/releases/download/v#{version}/penterep-linux-arm64"
      sha256 "02cc985953a307b8029ddbcdaf91a21f92be5e215e8124a0d446e6caa387487f"
    else
      url "https://github.com/Penterep/penterep-cli/releases/download/v#{version}/penterep-linux-x64"
      sha256 "7487167ce790a6343547e5cf3d1749fa5415f0b1f4a46ea88e6b56ca75c0f7df"
    end
  end

  def install
    binary = Dir.glob("penterep-*").first || "penterep"
    bin.install binary => "penterep"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/penterep --version")
  end
end
