# typed: false
# frozen_string_literal: true

# Auto-generated by CI. Do not edit manually.
# Source: https://github.com/Penterep/penterep-cli

class Penterep < Formula
  desc "AI-powered penetration testing CLI assistant"
  homepage "https://github.com/Penterep/penterep-cli"
  version "0.1.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-darwin-arm64"
      sha256 "8e8fd18a9cf40f2863c6a91de9769afd68ffb8562a25c4373e6078907bf8a258"
    else
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-darwin-x64"
      sha256 "a0376f6bfa46d26fed15ffab3b4868babe7b35157dcdadff50d217f09215fec0"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-linux-arm64"
      sha256 "9f64099b87b2de467468caa7e5111b58282b10d61051f6daf324b21099d77742"
    else
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-linux-x64"
      sha256 "e19608513f222c2f91b9d52ee03d9a78bcd96eb9662311c3ac6dbea8ee5a15e9"
    end
  end

  resource "assets" do
    url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-assets.tar.gz"
    sha256 "8b31139a3070f35d45cb9fdaeff2cc5f412147987016f585bbae06182d4decb9"
  end

  def install
    binary = Dir.glob("penterep-*").first || "penterep"
    bin.install binary => "penterep"

    # Extract sidecar assets next to the binary
    resource("assets").stage do
      (bin/"penterep-assets").install Dir["*"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/penterep --version")
  end
end
