# typed: false
# frozen_string_literal: true

# Auto-generated by CI. Do not edit manually.
# Source: https://github.com/Penterep/penterep-cli

class Penterep < Formula
  desc "AI-powered penetration testing CLI assistant"
  homepage "https://github.com/Penterep/penterep-cli"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-darwin-arm64"
      sha256 "bb7c7eed0404f669e5f33ad394f3ad8d647ad519b344f2c24b118e72ecf98167"
    else
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-darwin-x64"
      sha256 "16ecdafdde4ce091c7521899be3bbf677d7e749675ccd3e73192c7905b9f087c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-linux-arm64"
      sha256 "81d18b37c7bb98f58c6e957d174b09edbd75aa5c0bf1b79c6bc2e96a4cd571f6"
    else
      url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-linux-x64"
      sha256 "fa44efa9f7cb7b9c023d507476c12478185cb5965d2f21561cef67cfe6c08b7d"
    end
  end

  resource "assets" do
    url "https://github.com/penterep/cli/releases/download/v#{version}/penterep-assets.tar.gz"
    sha256 "abeea6b3dc85eafbe69b84ac2a5d90ad9ef9c2a4bfff0152f8b8a9f3fb1db4ea"
  end

  def install
    binary = Dir.glob("penterep-*").first || "penterep"
    bin.install binary => "penterep"

    # Extract sidecar assets next to the binary
    resource("assets").stage do
      (bin/"penterep-assets").install Dir["*"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/penterep --version")
  end
end
